### ISSUE TITLE
大佬能不能加个qq交流下

### ISSUE THREAD

**Issue by lopeasd** [Han-YLun/SaaS_IHRM#10]

**Comment by Han-YLun** [comment]
可以加这个群，都是目前在学习做这个系统的。
![微信图片_20200509133211.png](https://i.loli.net/2020/05/09/VlEOkTzPQtJ8U9c.png)

**Comment by alexgis08** [comment]
QQ群号是多少啊，图片显示不出来

**Comment by lopeasd** [comment]
已经没人说话了，你进群里问问
