### ISSUE TITLE
请问后端要怎么跑起来，没看明白orz

### ISSUE THREAD

**Issue by Harmon1a** [Han-YLun/SaaS_IHRM#14]

**Comment by Han-YLun** [comment]
clone下来后，分别启动每一个微服务的主Application就可以了

**Comment by Harmon1a** [comment]
你好，我把八个application开起来，sql数据库建好，redis也启动，前端按照您的git来配置好，改了config/index.js，跑起来后能显示界面，但是登陆按钮按下去后没有反应，请问这怎么办？大佬有qq或者其他联系方式可以咨询下吗

**Comment by Harmon1a** [comment]
我把config/index.js改回原来直接拉下来的9091端口，就成功了orz，还有个小问题，账号密码除了默认的，其他账号密码的在数据库里哪个table里

**Comment by Han-YLun** [comment]
在bs_user表中存放的，登录名是手机号，密码使用三次md5进行加密，手机号为salt；
建议配合b站视频一起学习。
如果有问题想交流可以加v：Daisuke-7
