### ISSUE TITLE
默认密码错误

### ISSUE THREAD

**Issue by wxb2dyj** [Han-YLun/SaaS_IHRM#15]
前端项目中配置的账号为13800000002，默认密码是123456，但是提示密码错误。

试了各种密码，什么admin，root都是错的。

所以密码是多少呢？

**Comment by Han-YLun** [comment]
如果是导入了我这边的数据库的，后端也都部署起来了，那登录密码就是123456。也有可能是你Redis未启动。
或者你把你数据的帐号和密码发给我看看。

**Comment by wxb2dyj** [comment]
我打印日志后发现提示我redis需要密码，然而我redis是配置了密码的。后来发现每个模块的代码中RedisManager并没有注入redis密码。你可能需要修改下ShiroConfiguration.java类。

**Comment by Han-YLun** [comment]
因为我这边是默认的，所以直接连接，你可以修改下，设置下帐号和密码。
