### ISSUE TITLE
不能注册

### ISSUE THREAD

**Issue by wxb2dyj** [Han-YLun/SaaS_IHRM#16]
作者你好，经过一番修改，现在能够进入后台管理系统了。界面很美观。
但是发现注册不了。
看了下前端代码，获取验证码的url路径/frame/register/verification_code在后端项目中没有找到，/frame开头的controller都没有。
请问作者，是我哪里弄错了什么，还是现在还没有开发注册功能？

**Comment by wxb2dyj** [comment]
能否拉我入群？前面的二维码已经过期了。

**Comment by Han-YLun** [comment]
是的，注册还没做。
注册涉及到注册的是企业还是员工还是saas管理员。
项目还存在很多问题和其他模块未设计完成。
这个我用来做了毕设，不过改了很多bug和一些模块我进行了重新设计。

微信群有效期至7/13
![微信图片_20200706154117](https://user-images.githubusercontent.com/44769070/86568261-2cc47800-bf9f-11ea-9cb6-9fa28d2966c3.jpg)

**Comment by wxb2dyj** [comment]
好的，谢谢！
