### ISSUE TITLE
登录调用login后，调用sys/profile接口报错，debug也没有进后台接口，是什么问题呢

### ISSUE THREAD

**Issue by alexgis08** [Han-YLun/SaaS_IHRM#24]
![image](https://user-images.githubusercontent.com/13539371/102868141-c829a680-4474-11eb-84f1-8d24b13bd7ed.png)

**Comment by Han-YLun** [comment]
是不是redis没配置

**Comment by alexgis08** [comment]
Redis安装默认配置启动，端口6379，哪里还需要配置么

**Comment by Han-YLun** [comment]
不好意思,工作太忙,这么久才回复你，这边请求应该是你这边没配置的问题
![image](https://user-images.githubusercontent.com/44769070/103450662-78f53880-4cf4-11eb-9823-4121abbe348c.png)
