### ISSUE TITLE
大佬可以出一下项目部署运行的教程嘛？球球

### ISSUE THREAD

**Issue by JH-hard** [Han-YLun/SaaS_IHRM#26]
#

**Comment by Han-YLun** [comment]
好的，这周末出

**Comment by Han-YLun** [comment]
前端部署教程：[https://www.cnblogs.com/ArvinYL/p/14457187.html](https://www.cnblogs.com/ArvinYL/p/14457187.html)
后端部署教程 : [https://www.cnblogs.com/ArvinYL/p/14460255.html](https://www.cnblogs.com/ArvinYL/p/14460255.html)

**Comment by jack13163** [comment]
您好！    您的邮件已送到，我会及时答复，请耐心等待！
