### ISSUE TITLE
楼主，我在运行的时候按照顺序把前8个跑起来了，最后一个audit没能跑成功，我把错误放下面，能看看嘛

### ISSUE THREAD

**Issue by castive** [Han-YLun/SaaS_IHRM#44]
The web application [ROOT] appears to have started a thread named [spring.cloud.inetutils] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

**Comment by Han-YLun** [comment]
看提示说是内存泄露问题，idea重启下或者电脑重启下，再试下
