### ISSUE TITLE
AuditApplication这个服务启动不起来，作者能帮忙看一下吗。谢谢

### ISSUE THREAD

**Issue by caryyang0501** [Han-YLun/SaaS_IHRM#49]
![image](https://user-images.githubusercontent.com/127370406/225840896-4fe78910-e3c2-4fc5-bc92-462788f04c4d.png)

**Comment by Han-YLun** [comment]
试下这个：https://blog.csdn.net/qq_41520636/article/details/118341025

**Comment by caryyang0501** [comment]
可以了，谢谢
