### ISSUE TITLE
数据库搭建

### ISSUE THREAD

**Issue by Tomwillan** [Han-YLun/SaaS_IHRM#54]
act和ihrm这两个sql文件要怎么搭建成数据库呀，是都放在一个数据库，还是新建act和ihrm这两个数据库？

**Comment by jack13163** [comment]
您好！    您的邮件已送到，我会及时答复，请耐心等待！

**Comment by Han-YLun** [comment]
> act和ihrm这两个sql文件要怎么搭建成数据库呀，是都放在一个数据库，还是新建act和ihrm这两个数据库？
数据库下面可以有多个 schema，每个 schema下面有多个表，对应两个 schema
